name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

      # install latest pspdev sdk
    - name: Install mingw
      run: |
        sudo apt update
        sudo apt install -y g++-mingw-w64-i686 g++-mingw-w64

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Build
      run: |
        bash build.sh

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBE_networking_injector_${{ env.sha_name }}
        path: |
           release
        if-no-files-found: error
